/** PHASE 8 - atomic stock ledger and inventory. */
var StockLedger = {
  headers:function(){return ['Ledger_ID','Product_ID','Type','Quantity','Stock_Before','Stock_After','Reference','Unit_Cost','Date','CreatedAt','UpdatedAt','User_ID'];},
  sheet:function(){return SheetStore.ensureSheet_('Stock_Ledger',this.headers());},
  appendAtomic_:function(user,productId,type,qty,before,after,reference,unitCost,date){
    var sh=this.sheet(), id=Utilities.getUuid(); SheetStore.append_(sh,{Ledger_ID:id,Product_ID:productId,Type:type,Quantity:Number(qty||0),Stock_Before:Number(before||0),Stock_After:Number(after||0),Reference:reference||'',Unit_Cost:Number(unitCost||0),Date:date||new Date().toISOString().slice(0,10),CreatedAt:new Date().toISOString(),UpdatedAt:new Date().toISOString(),User_ID:user&&user.userId||''}); return id;
  },
  list:function(user,payload){requireRole_(user,['ADMIN','STAFF']);var rows=SheetStore.records_(this.sheet());if(payload&&payload.productId)rows=rows.filter(function(r){return String(r.Product_ID)===String(payload.productId);});return ok_(rows.map(function(r){return {id:String(r.Ledger_ID),productId:String(r.Product_ID),type:String(r.Type),qty:Number(r.Quantity||0),stockBefore:Number(r.Stock_Before||0),stockAfter:Number(r.Stock_After||0),reference:String(r.Reference||''),unitCost:Number(r.Unit_Cost||0),date:String(r.Date||''),createdAt:String(r.CreatedAt||''),updatedAt:String(r.UpdatedAt||'')};}));
  }
};
var Inventory = {list:function(user,payload){requireRole_(user,['ADMIN','STAFF']);var rows=SheetStore.records_(Products.sheet()).filter(function(r){return String(r.Active).toLowerCase()!=='false';}).map(productRowToObj_);return ok_(rows.map(function(p){p.lowStock=p.currentStock<=p.reorderLevel;return p;}));}, adjust:function(user,payload){requireRole_(user,['ADMIN']);var id=clean_(payload&&payload.productId), sh=Products.sheet(), r=SheetStore.findBy_(sh,'Product_ID',id);if(!r)return fail_('PRODUCT_NOT_FOUND','Product not found.');var qty=Number(payload.qty||0),before=Number(r.Current_Stock||0),after=before+qty;if(after<0)return fail_('INSUFFICIENT_STOCK','Stock cannot go below zero.');var now=new Date().toISOString();SheetStore.updateBy_(sh,'Product_ID',id,{Current_Stock:after,UpdatedAt:now,Version:Number(r.Version||1)+1});StockLedger.appendAtomic_(user,id,clean_(payload.type||'Adjustment'),qty,before,after,clean_(payload.reference),Number(payload.unitCost||r.Purchase_Price||0),clean_(payload.date)||now.slice(0,10));Audit.write_(user,'STOCK_ADJUST','Inventory',id,payload);return ok_({productId:id,stockBefore:before,stockAfter:after});}};
