/** PHASE 8 - authoritative sale: validates stock, writes sale/items/ledger/due atomically. */
var Sales = {
 headers:function(){return ['Sale_ID','Date','Customer_ID','Invoice_No','Subtotal','Discount','Commission','Total_Bill','Previous_Due','Total_Payable','Paid_Amount','Payment_Method','New_Due','Invoice_Img','Cost_Of_Goods','CreatedAt','UpdatedAt','User_ID','Version'];},
 itemHeaders:function(){return ['Sale_Item_ID','Sale_ID','Product_ID','Quantity','Unit_Price','Unit_Cost','Line_Total','CreatedAt'];},
 sheet:function(){return SheetStore.ensureSheet_('Sales',this.headers());}, itemSheet:function(){return SheetStore.ensureSheet_('Sale_Items',this.itemHeaders());},
 create:function(user,payload){
  requireRole_(user,['ADMIN','STAFF']); payload=payload||{}; var id=clean_(payload.id||payload.saleId)||Utilities.getUuid(),sh=this.sheet(); if(SheetStore.findBy_(sh,'Sale_ID',id))return ok_({saleId:id,duplicate:true});
  var items=Array.isArray(payload.items)?payload.items:[]; if(!items.length)return fail_('EMPTY_SALE','Sale items required.'); var psh=Products.sheet(), checked=[],subtotal=0,cost=0;
  items.forEach(function(it){var pid=clean_(it.productId),p=SheetStore.findBy_(psh,'Product_ID',pid);if(!p)throw new Error('Product not found: '+pid);var q=Number(it.qty||0);if(q<=0)throw new Error('Invalid sale quantity.');var stock=Number(p.Current_Stock||0);if(stock<q)throw new Error('Insufficient stock for '+p.Name);var up=Number(it.sellingPrice!=null?it.sellingPrice:p.Selling_Price||0),uc=Number(p.Purchase_Price||0);subtotal+=q*up;cost+=q*uc;checked.push({it:it,p:p,q:q,up:up,uc:uc});});
  var discount=Math.max(0,Number(payload.discount||0)),commission=Math.max(0,Number(payload.commission||0)),net=Math.max(0,subtotal-discount-commission); var customerId=clean_(payload.customerId), customer=null,prev=0;
  if(customerId){customer=SheetStore.findBy_(SheetStore.ensureSheet_('Customers',['Cust_ID','Name','Shop_Name','Phone','WhatsApp','Address','NID','Opening_Due','Date','Current_Due','Profile_Pic','Note']),'Cust_ID',customerId);if(!customer)return fail_('CUSTOMER_NOT_FOUND','Customer not found.');prev=Number(customer.Current_Due||0);}
  var payable=prev+net,paid=Math.min(Math.max(0,Number(payload.paidAmount||0)),payable),newDue=Math.max(0,payable-paid),now=new Date().toISOString(),invoice=clean_(payload.invoice||payload.invoiceNo)||('INV-'+Date.now());
  sh=this.sheet();SheetStore.append_(sh,{Sale_ID:id,Date:payload.date||now.slice(0,10),Customer_ID:customerId,Invoice_No:invoice,Subtotal:subtotal,Discount:discount,Commission:commission,Total_Bill:net,Previous_Due:prev,Total_Payable:payable,Paid_Amount:paid,Payment_Method:clean_(payload.paymentMethod)||'Cash',New_Due:newDue,Invoice_Img:clean_(payload.invoiceImg),Cost_Of_Goods:cost,CreatedAt:now,UpdatedAt:now,User_ID:user.userId||'',Version:1});
  var ish=this.itemSheet();checked.forEach(function(x){var before=Number(x.p.Current_Stock||0),after=before-x.q;SheetStore.append_(ish,{Sale_Item_ID:Utilities.getUuid(),Sale_ID:id,Product_ID:x.p.Product_ID,Quantity:x.q,Unit_Price:x.up,Unit_Cost:x.uc,Line_Total:x.q*x.up,CreatedAt:now});SheetStore.updateBy_(psh,'Product_ID',x.p.Product_ID,{Current_Stock:after,UpdatedAt:now,Version:Number(x.p.Version||1)+1});StockLedger.appendAtomic_(user,x.p.Product_ID,'Sale',-x.q,before,after,invoice,x.uc,payload.date||now.slice(0,10));});
  if(customer){SheetStore.updateBy_(SheetStore.ensureSheet_('Customers',['Cust_ID','Name','Shop_Name','Phone','WhatsApp','Address','NID','Opening_Due','Date','Current_Due','Profile_Pic','Note']),'Cust_ID',customerId,{Current_Due:newDue});SheetStore.append_(SheetStore.ensureSheet_('Customer_Transactions',['Transaction_ID','Customer_ID','Type','Date','Bill','Payment','Remaining_Due','Reference','Method','Note','CreatedAt','UpdatedAt'] ),{Transaction_ID:Utilities.getUuid(),Customer_ID:customerId,Type:'Sale',Date:payload.date||now.slice(0,10),Bill:net,Payment:paid,Remaining_Due:newDue,Reference:invoice,Method:clean_(payload.paymentMethod)||'Cash',Note:clean_(payload.note),CreatedAt:now,UpdatedAt:now});}
  Audit.write_(user,'SALE_CREATE','Sales',id,payload);return ok_({saleId:id,invoice:invoice,totalBill:net,costOfGoods:cost,profit:net-cost,previousDue:prev,paidAmount:paid,newDue:newDue});
 }
};
