/** PHASE 8 - supplier master and due ledger. */
var Suppliers = {
 headers:function(){return ['Supplier_ID','Name','Shop_Name','Phone','WhatsApp','Address','Opening_Due','Current_Due','Note','Active','CreatedAt','UpdatedAt','Version'];},
 txHeaders:function(){return ['Transaction_ID','Supplier_ID','Type','Date','Reference','Bill','Previous_Due','Payment','Discount','Remaining_Due','Method','Note','CreatedAt','UpdatedAt','User_ID'];},
 sheet:function(){return SheetStore.ensureSheet_('Suppliers',this.headers());}, txSheet:function(){return SheetStore.ensureSheet_('Supplier_Transactions',this.txHeaders());},
 list:function(user,payload){requireRole_(user,['ADMIN','STAFF']);var a=SheetStore.records_(this.sheet());var q=clean_(payload&&payload.query).toLowerCase();if(q)a=a.filter(function(r){return [r.Name,r.Shop_Name,r.Phone,r.WhatsApp].some(function(v){return String(v||'').toLowerCase().indexOf(q)>=0;});});return ok_(a.map(supplierRow_));},
 create:function(user,payload){requireRole_(user,['ADMIN','STAFF']);var id=clean_(payload&&payload.id||payload&&payload.supplierId)||Utilities.getUuid(),sh=this.sheet();if(SheetStore.findBy_(sh,'Supplier_ID',id))return ok_({supplierId:id,duplicate:true});var d=Number(payload.openingDue||0),now=new Date().toISOString();SheetStore.append_(sh,{Supplier_ID:id,Name:clean_(payload.name),Shop_Name:clean_(payload.shop),Phone:clean_(payload.mobile||payload.phone),WhatsApp:clean_(payload.whatsapp),Address:clean_(payload.address),Opening_Due:d,Current_Due:d,Note:clean_(payload.note),Active:true,CreatedAt:payload.createdAt||now,UpdatedAt:now,Version:1});if(d) this.addTx_(user,id,'Opening Due',payload.date||now.slice(0,10), 'OPENING',0,0,0,0,d,'',payload.note);Audit.write_(user,'SUPPLIER_CREATE','Suppliers',id,payload);return ok_({supplierId:id,currentDue:d});},
 payment:function(user,payload){requireRole_(user,['ADMIN','STAFF']);var id=clean_(payload.supplierId),sh=this.sheet(),s=SheetStore.findBy_(sh,'Supplier_ID',id);if(!s)return fail_('SUPPLIER_NOT_FOUND','Supplier not found.');var cur=Number(s.Current_Due||0),disc=Math.min(Math.max(0,Number(payload.discount||0)),cur),paid=Math.min(Math.max(0,Number(payload.paidAmount||0)),Math.max(0,cur-disc)),rem=Math.max(0,cur-disc-paid),now=new Date().toISOString();SheetStore.updateBy_(sh,'Supplier_ID',id,{Current_Due:rem,UpdatedAt:now,Version:Number(s.Version||1)+1});var tx=this.addTx_(user,id,'Payment',payload.date||now.slice(0,10),clean_(payload.reference),0,cur,paid,disc,rem,clean_(payload.paymentMethod||payload.method)||'Cash',clean_(payload.note));Audit.write_(user,'SUPPLIER_PAYMENT','Suppliers',id,payload);return ok_({supplierId:id,previousDue:cur,discount:disc,paidAmount:paid,remainingDue:rem});},
 addPurchaseDue_:function(user,id,amount,reference,date){var sh=this.sheet(),s=SheetStore.findBy_(sh,'Supplier_ID',id);if(!s)throw new Error('Supplier not found.');var cur=Number(s.Current_Due||0),rem=cur+Number(amount||0),now=new Date().toISOString();SheetStore.updateBy_(sh,'Supplier_ID',id,{Current_Due:rem,UpdatedAt:now,Version:Number(s.Version||1)+1});this.addTx_(user,id,'Purchase',date,reference,Number(amount||0),cur,0,0,rem,'', 'Purchase due');},
 addTx_:function(user,id,type,date,reference,bill,previous,payment,discount,remaining,method,note){var now=new Date().toISOString();var tid=Utilities.getUuid();SheetStore.append_(this.txSheet(),{Transaction_ID:tid,Supplier_ID:id,Type:type,Date:date,Reference:reference||'',Bill:Number(bill||0),Previous_Due:Number(previous||0),Payment:Number(payment||0),Discount:Number(discount||0),Remaining_Due:Number(remaining||0),Method:method||'',Note:note||'',CreatedAt:now,UpdatedAt:now,User_ID:user&&user.userId||''});return tid;},
 transactions:function(user,payload){requireRole_(user,['ADMIN','STAFF']);var a=SheetStore.records_(this.txSheet());if(payload&&payload.supplierId)a=a.filter(function(r){return String(r.Supplier_ID)===String(payload.supplierId);});return ok_(a);}
};
function supplierRow_(r){return {id:String(r.Supplier_ID),supplierId:String(r.Supplier_ID),name:String(r.Name||''),shop:String(r.Shop_Name||''),mobile:String(r.Phone||''),whatsapp:String(r.WhatsApp||''),address:String(r.Address||''),openingDue:Number(r.Opening_Due||0),currentDue:Number(r.Current_Due||0),note:String(r.Note||''),active:String(r.Active).toLowerCase()!=='false',createdAt:String(r.CreatedAt||''),updatedAt:String(r.UpdatedAt||''),version:Number(r.Version||1)};}
