/** PHASE 8 - duplicate-safe authoritative sync for all business entities. */
var Sync = {
 push:function(user,payload){var items=payload&&Array.isArray(payload.items)?payload.items:[];var out=[];for(var i=0;i<items.length;i++){var item=items[i],lock=LockService.getScriptLock();try{lock.waitLock(15000);var r=applySync8_(user,item);out.push({syncId:String(item.syncId||item.mutationId||''),status:r.duplicate?'DUPLICATE':'SYNCED',data:r.data||r});}catch(e){out.push({syncId:String(item&&(item.syncId||item.mutationId)||''),status:'FAILED',error:String(e.message||e)});}finally{try{lock.releaseLock();}catch(_) {}}}return ok_({results:out});},
 pull:function(user,payload){requireRole_(user,['ADMIN','STAFF']);var since=payload&&payload.since?new Date(payload.since):new Date(0),out=[];var defs=[['Customers','customer'],['Products','product'],['Sales','sale'],['Sale_Items','sale_item'],['Purchases','purchase'],['Purchase_Items','purchase_item'],['Suppliers','supplier'],['Supplier_Transactions','supplier_transaction'],['Expenses','expense'],['Stock_Ledger','stock_ledger'],['Due_Payments','payment'],['Due_Add','due'],['Reminders','reminder']];defs.forEach(function(d){var sh=getDb_().getSheetByName(d[0]);if(!sh)return;SheetStore.records_(sh).forEach(function(r){var dt=new Date(r.UpdatedAt||r.CreatedAt||r.Date||0);if(dt>=since)out.push({entity:d[1],payload:normalize8_(d[1],r)});});});return ok_({changes:out,serverTime:new Date().toISOString()});}
};
function applySync8_(user,item){if(!item||!item.entity||!item.operation)throw new Error('Invalid sync item.');var mid=clean_(item.mutationId||item.syncId);if(!mid)throw new Error('mutationId/syncId required.');var msh=SheetStore.ensureSheet_('Sync_Mutations',['Mutation_ID','Entity','Operation','User_ID','CreatedAt','Result_JSON']);var old=SheetStore.findBy_(msh,'Mutation_ID',mid);if(old)return {duplicate:true,data:old.Result_JSON?JSON.parse(old.Result_JSON):{mutationId:mid}};var e=String(item.entity).toLowerCase(),op=String(item.operation).toUpperCase(),p=item.payload||{},result;
 switch(e){case 'product':requireRole_(user,['ADMIN']);result=op==='CREATE'?JSON.parse(unwrap_(Products.create(user,p))).data:op==='UPDATE'?JSON.parse(unwrap_(Products.update(user,p))).data:throwErr_('Unsupported product operation.');break;
 case 'purchase':requireRole_(user,['ADMIN','STAFF']);if(op!=='CREATE')throwErr_('Unsupported purchase operation.');result=JSON.parse(unwrap_(Purchases.create(user,p))).data;break;
 case 'sale':requireRole_(user,['ADMIN','STAFF']);if(op!=='CREATE')throwErr_('Unsupported sale operation.');result=JSON.parse(unwrap_(Sales.create(user,p))).data;break;
 case 'supplier':requireRole_(user,['ADMIN','STAFF']);result=op==='CREATE'?JSON.parse(unwrap_(Suppliers.create(user,p))).data:op==='UPDATE'?supplierUpdateSync_(user,p):throwErr_('Unsupported supplier operation.');break;
 case 'supplier_payment':requireRole_(user,['ADMIN','STAFF']);if(op!=='CREATE')throwErr_('Unsupported supplier payment operation.');result=JSON.parse(unwrap_(Suppliers.payment(user,p))).data;break;
 case 'supplier_transaction':requireRole_(user,['ADMIN','STAFF']);result={ignored:true,reason:'Generated server-side by supplier purchase/payment'};break;
 case 'expense':requireRole_(user,['ADMIN']);if(op!=='CREATE')throwErr_('Unsupported expense operation.');result=JSON.parse(unwrap_(Expenses.create(user,p))).data;break;
 case 'stock_ledger':requireRole_(user,['ADMIN']);result={ignored:true,reason:'Stock ledger is generated server-side by product/purchase/sale mutations'};break;
 case 'inventory':requireRole_(user,['ADMIN']);result={ignored:true};break;
 case 'customer':requireRole_(user,['ADMIN','STAFF']);result=legacySyncEntity_(user,e,op,p);break;
 case 'payment':case 'due':case 'reminder':result=legacySyncEntity_(user,e,op,p);break;
 default:throwErr_('Unsupported sync entity: '+e);}
 SheetStore.append_(msh,{Mutation_ID:mid,Entity:e,Operation:op,User_ID:user.userId||'',CreatedAt:new Date().toISOString(),Result_JSON:JSON.stringify(result||{})});return {duplicate:false,data:result};}
function supplierUpdateSync_(user,p){var id=clean_(p.id||p.supplierId),sh=Suppliers.sheet(),r=SheetStore.findBy_(sh,'Supplier_ID',id);if(!r)throw new Error('Supplier not found.');SheetStore.updateBy_(sh,'Supplier_ID',id,{Name:p.name!=null?clean_(p.name):r.Name,Shop_Name:p.shop!=null?clean_(p.shop):r.Shop_Name,Phone:p.mobile!=null?clean_(p.mobile):r.Phone,WhatsApp:p.whatsapp!=null?clean_(p.whatsapp):r.WhatsApp,Address:p.address!=null?clean_(p.address):r.Address,Note:p.note!=null?clean_(p.note):r.Note,UpdatedAt:new Date().toISOString(),Version:Number(r.Version||1)+1});return supplierRow_(SheetStore.findBy_(sh,'Supplier_ID',id));}
function legacySyncEntity_(user,e,op,p){if(e==='customer'){if(op==='CREATE')return JSON.parse(unwrap_(Customers.create(user,p))).data;if(op==='UPDATE')return JSON.parse(unwrap_(Customers.update(user,p))).data;if(op==='DELETE'){requireRole_(user,['ADMIN']);return JSON.parse(unwrap_(Customers.remove(user,p))).data;}}if(e==='payment'&&op==='CREATE')return JSON.parse(unwrap_(Payments.create(user,p))).data;if(e==='due'&&op==='CREATE')return JSON.parse(unwrap_(Due.create(user,p))).data;if(e==='reminder'&&(op==='CREATE'||op==='UPDATE'))return JSON.parse(unwrap_(Reminders.save(user,p))).data;if(e==='reminder'&&op==='DELETE')return JSON.parse(unwrap_(Reminders.disable(user,p))).data;throw new Error('Unsupported operation.');}
function throwErr_(m){throw new Error(m);}
function normalize8_(e,r){if(e==='customer')return normalizeCustomer_(r);if(e==='product')return productRowToObj_(r);if(e==='supplier')return supplierRow_(r);return r;}
